export { default as Soccer } from './soccer.svg';
export { default as Basketball } from './basketball.svg';
export { default as Tennis } from './tennis.svg';
export { default as Run } from './running.svg';
export { default as Skateboarding } from './skateboarding.svg';
export { default as Bmx } from './directions-bike.svg';
export { default as Roller } from './roller-skating.svg';
export { default as Bike } from './pedal-bike.svg';
export { default as Snowboard } from './snowboarding.svg';
