APP_NAME: "front-app"
APP_IMAGE_NAME: "harbor.itm-space.net/front/sport-unite-sport-unite-develop"
APP_IMAGE_TAG: "latest"
INGRESS_HOST: "dev.sport-unite.it-mentor.space"

VITE_KEYCLOAK_URL: "http://keycloak.it-mentor.space/"
VITE_TOKEN_URL: "realms/itm-platform-dev/protocol/openid-connect/token"
VITE_CLIENT_SECRET: "z0E6Cruf5PuJ98z9R9q54bTPsQoVWq8j"
VITE_BASE_URL: "http://api-gateway.dev.sport-unite.it-mentor.space"

replicaCount: 1

app:
  listen:
    port: 3000

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

tls:
  enabled: true
  issuer: "letsencrypt"

