import { API_PATHS } from '@shared/lib';

export const ApiEndpoints = {
  GET_MY_USER: `/${API_PATHS.USER_SERVICE}/users/me`,
  CREATE_USER: `/${API_PATHS.USER_SERVICE}/users`,
  EVENTS_SEARCH: `/${API_PATHS.EVENT_SERVICE}/events/search`,
  EVENTS_TYPES: `/${API_PATHS.EVENT_SERVICE}/events/types`,
  EVENT_BY_ID: `/${API_PATHS.EVENT_SERVICE}/events`,
  USER_CHATS: `/${API_PATHS.CHAT_SERVICE}/chat-rooms/my`,
  CHAT_MESSAGES: `/${API_PATHS.CHAT_SERVICE}/chat-rooms`,
  USER_EVENTS: `/${API_PATHS.EVENT_SERVICE}/events/user`,
  GET_NOTIFICATIONS: `/${API_PATHS.NOTIFICATION_SERVICE}/inapp`,
  GET_COUNT_NOTIFICATIONS: `/${API_PATHS.NOTIFICATION_SERVICE}/inapp/count`,
  MARK_AS_READ_NOTIFICATIONS: `/${API_PATHS.NOTIFICATION_SERVICE}/inapp/read`,
  DELETE_NOTIFICATIONS: `/${API_PATHS.NOTIFICATION_SERVICE}/inapp/delete`,
  CREATE_EVENT: `/${API_PATHS.EVENT_SERVICE}/events`,
  UPLOAD_PHOTO: `/${API_PATHS.IMAGE_SERVICE}/resources/images`,
} as const;

export const TWO_GIS_API_BASE_URL = 'https://catalog.api.2gis.com/3.0';
